$t('total.element')
$t('total.ae')
$t('total.pr')
$t('total.fcp')
$t('total.music')
$t('total.sfx')
$t('total.3d')
$t('total.video')
$t('total.image')
$t('total.gif')

$t('total.free.element')
$t('total.free.ae')
$t('total.free.music')
$t('total.free.video')
$t('total.free.gif')
