version: 2.1

workflows:
  version: 2.1
  build_frontend_modules:
    jobs:
      - unit_test

jobs:
  unit_test:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependency
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Unit Tests (master, dev)"
          command: npm run test:unit || exit 1;
