const appMediaTypeList = [
  // After Effects
  {
    id: 'ae',
    mt: 'ae',
    code: null,
    value: ['8', '19'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-after-effects-square',
    iconClassSecond: 'icon-after-effects',
    api: 'ae',
    mainMediaType: 'ae',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'ae-template',
    mt: '8',
    code: 8,
    value: ['8'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-after-effects-square',
    iconClassSecond: 'icon-after-effects',
    api: 'ae-template',
    mainMediaType: 'ae',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'ae-preset',
    mt: '19',
    code: 19,
    value: ['19'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-after-effects-square',
    iconClassSecond: 'icon-after-effects',
    api: 'ae-preset',
    mainMediaType: 'ae',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },

  // Premiere Pro
  {
    id: 'pr',
    mt: 'pr',
    code: null,
    value: ['15', '16', '20'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-premiere-pro',
    iconClassSecond: 'icon-premiere-pro',
    api: 'pr',
    mainMediaType: 'pr',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'pr-template',
    mt: '15',
    code: 15,
    value: ['15'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-premiere-pro',
    iconClassSecond: 'icon-premiere-pro',
    api: 'pr-template',
    mainMediaType: 'pr',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'pr-preset',
    mt: '20',
    code: 20,
    value: ['20'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-premiere-pro',
    iconClassSecond: 'icon-premiere-pro',
    api: 'pr-preset',
    mainMediaType: 'pr',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'mg-template',
    mt: '16',
    code: 16,
    value: ['16'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-mogrt',
    iconClassSecond: 'icon-mogrt',
    api: 'mg-template',
    mainMediaType: 'mg-template',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },

  // Videos
  {
    id: 'video',
    mt: 'video',
    code: null,
    value: ['3', '4'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-video',
    iconClassSecond: 'icon-video',
    api: 'video',
    mainMediaType: 'video',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'animation',
    mt: '3',
    code: 3,
    value: ['3'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-animation',
    iconClassSecond: 'icon-animation',
    api: 'animation',
    mainMediaType: 'video',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'video-live',
    mt: '4',
    code: 4,
    value: ['4'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-video',
    iconClassSecond: 'icon-video',
    api: 'video-live',
    mainMediaType: 'video',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'video-vr',
    mt: '12',
    code: 12,
    value: ['12'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-vr',
    iconClassSecond: 'icon-vr',
    api: 'video-vr',
    mainMediaType: 'video',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },

  // Music
  {
    id: 'music',
    mt: '6',
    code: 6,
    value: ['6'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-music',
    iconClassSecond: 'icon-music',
    api: 'music',
    mainMediaType: 'music',
    isMainMediaType: true,
    isAudio: true,
    isImage: false,
  },

  // Image
  {
    id: 'image',
    mt: 'image',
    code: null,
    value: ['1', '2', '14'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-image',
    iconClassSecond: 'icon-image',
    api: 'image',
    mainMediaType: 'image',
    isMainMediaType: true,
    isAudio: false,
    isImage: true,
  },
  {
    id: 'photo',
    mt: '1',
    code: 1,
    value: ['1'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-image',
    iconClassSecond: 'icon-image',
    api: 'photo',
    mainMediaType: 'image',
    isMainMediaType: true,
    isAudio: false,
    isImage: true,
  },
  {
    id: 'vector',
    mt: '2',
    code: 2,
    value: ['2'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-vector',
    iconClassSecond: 'icon-vector',
    api: 'vector',
    mainMediaType: 'image',
    isMainMediaType: false,
    isAudio: false,
    isImage: true,
  },
  {
    id: 'gif',
    mt: '14',
    code: 14,
    value: ['14'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-images',
    iconClassSecond: 'icon-images',
    api: 'gif',
    mainMediaType: 'image',
    isMainMediaType: false,
    isAudio: false,
    isImage: true,
  },

  // Sound effect - SFX
  {
    id: 'sfx',
    mt: '7',
    code: 7,
    value: ['7'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-sfx',
    iconClassSecond: 'icon-sfx',
    api: 'sfx',
    mainMediaType: 'sfx',
    isMainMediaType: true,
    isAudio: true,
    isImage: false,
  },

  // Apple Motion Templates
  {
    id: 'fcp',
    mt: 'fcp',
    code: null,
    value: ['9'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-apple-motion',
    iconClassSecond: 'icon-apple-motion',
    api: 'fcp',
    mainMediaType: 'fcp',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },
  {
    id: 'motion-template',
    mt: '9',
    code: 9,
    value: ['9'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-apple-motion',
    iconClassSecond: 'icon-apple-motion',
    api: 'motion-template',
    mainMediaType: 'fcp',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },

  // 3D Models
  {
    id: '3d',
    mt: '3d',
    code: null,
    value: ['5'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-3d-model',
    iconClassSecond: 'icon-3d-model',
    api: '3d',
    mainMediaType: '3d',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },
  {
    id: '3d-model',
    mt: '5',
    code: 5,
    value: ['5'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-3d-model',
    iconClassSecond: 'icon-3d-model',
    api: '3d-model',
    mainMediaType: '3d',
    isMainMediaType: false,
    isAudio: false,
    isImage: false,
  },

  // lottie
  {
    id: 'lottie',
    mt: '21',
    code: 21,
    value: ['21'],
    name: '',
    nameShort: '',
    iconClassDefault: 'icon-lottie',
    iconClassSecond: 'icon-lottie',
    api: 'lottie',
    mainMediaType: 'lottie',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
  },
  // resolve
  {
    id: 'resolve',
    mt: 'resolve',
    code: null,
    value: ['22', '23'],
    iconClassDefault: 'icon-davinci-resolve',
    iconClassSecond: 'icon-davinci-resolve-outline',
    api: 'resolve',
    mainMediaType: 'resolve',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
    hasAiSearch: false,
  },
  {
    id: 'resolve-template',
    mt: '22',
    code: 22,
    value: ['22'],
    iconClassDefault: 'icon-davinci-resolve',
    iconClassSecond: 'icon-davinci-resolve-outline',
    api: 'resolve-template',
    mainMediaType: 'resolve',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
    hasAiSearch: false,
  },
  {
    id: 'resolve-macro',
    mt: '23',
    code: 23,
    value: ['23'],
    iconClassDefault: 'icon-davinci-resolve',
    iconClassSecond: 'icon-davinci-resolve-outline',
    api: 'resolve-macro',
    mainMediaType: 'resolve',
    isMainMediaType: true,
    isAudio: false,
    isImage: false,
    hasAiSearch: false,
  },
];

export default appMediaTypeList;
